var lang = {
    choose_value: 'Search Options',
    search_value: 'Select',
    select_all: 'Select All',
    unselect_all: 'Unselect All',
    selected_option: ' selected',
    dt_search: 'Search...',
    dt_datatable_pagination_info: 'Showing _START_ to _END_ of _TOTAL_ entries',
    dt_next: 'Next <i class="ph ph-caret-right"></i>',
    dt_next_text: 'Next',
    dt_previous: '<i class="ph ph-caret-left"></i> Prev',
    dt_first: '<i class="ph ph-caret-double-left"></i> First',
    dt_last: 'Last <i class="ph ph-caret-double-right"></i>',
    dt_datatable_pagination_show_menu: 'Show _MENU_ entries',
    dt_view_all: 'View All',
    dt_view_less: 'View Less',
    dt_datatable_empty_table: 'No matching records found',
    dt_datatable_info_filtered: '(filtered from _MAX_ total entries)',
    dt_pagination_label: 'Page {0}',
    collapse_all: 'Collapse All',
    expand_all: 'Expand All',
    govbh_show: 'Show',
    govbh_hide: 'Hide',
    swal_ok: 'Ok',
    swal_confirm: 'Confirm',
    swal_cancel: 'Cancel',
    swal_close: 'Close',    
    swal_days: 'Days',
    swal_hours: 'Hours',
    swal_minutes: 'Minutes',
    swal_seconds: 'Seconds',
    days: 'Days',
    hours: 'Hours',
    minutes: 'Minutes',
    seconds: 'Seconds',
    govbh_pause_video: 'Click here to pause video.',
    govbh_play_video: 'Click here to play video.',
    govbh_slider_slide_aria_label: 'Slide {0} of {1}',
    govbh_slider_button_aria_label: 'Show slide {0}',
    slide_text: 'Slide',
    of_text: 'of',
    show_image: 'Show image',
    govbh_yes: 'Yes',
    govbh_no: 'No',
    showmoretext:'Show more breadcrumbs',
    govbh_next_gallery: 'Next Gallery Item',
    govbh_prev_gallery: 'Prev Gallery Item',
    govbh_play_gallery: 'Play Gallery Slideshow',
    govbh_close_gallery: 'Close Gallery',
    govbh_max_files_allowed: 'Maximum {0} files allowed',
    govbh_file_exceeds: 'File {0} {1} exceeds {2}MB',
}