var lang = {
    choose_value: 'Search Options',
    search_value: 'Select',
    select_all: 'Select All',
    unselect_all: 'Unselect All',
    selected_option: ' selected',
    dt_search: 'البحث...',
    dt_datatable_pagination_info: 'عرض _START_ ل _END_ ل _TOTAL_ المدخلات',
    dt_next: 'التالية <i class="ph ph-caret-right"></i>',
    dt_next_text: 'التالية',
    dt_previous: '<i class="ph ph-caret-left"></i> السابقة',
    dt_first: '<i class="ph ph-caret-double-left"></i> الأولى',
    dt_last: 'الأخيرة <i class="ph ph-caret-double-right"></i>',
    dt_datatable_pagination_show_menu: 'إظهار _MENU_ المدخلات',
    dt_view_all: 'View All',
    dt_view_less: 'View Less',
    dt_datatable_empty_table: 'No matching records found',
    dt_datatable_info_filtered: '(filtered from _MAX_ total المدخلات)',
    dt_pagination_label: 'الصفحة {0}',
    collapse_all: 'إخفاء الكل',
    expand_all: 'إظهار الكل',
    govbh_show: 'إظهار',
    govbh_hide: 'إخفاء',
    swal_ok: 'موافق',
    swal_confirm: 'تأكيد',
    swal_cancel: 'إلغاء',
    swal_close: 'Close',    
    swal_days: 'يوم',
    swal_hours: 'ساعة',
    swal_minutes: 'دقيقة',
    swal_seconds: 'ثواني',
    days: 'يوم',
    hours: 'ساعة',
    minutes: 'دقيقة',
    seconds: 'ثواني',
    govbh_pause_video: 'Click here to pause video.',
    govbh_play_video: 'Click here to play video.',
    govbh_slider_slide_aria_label: 'Slide {0} of {1}',
    govbh_slider_button_aria_label: 'Show slide {0}',
    slide_text: 'شريحة',
    of_text: 'من',
    show_image: 'Show image',
    govbh_yes: 'نعم',
    govbh_no: 'لا',
    showmoretext:'عرض المزيد من فتات الخبز',
    govbh_next_gallery: 'العنصر التالي في المعرض',
    govbh_prev_gallery: 'العنصر السابق في المعرض',
    govbh_play_gallery: 'تشغيل عرض شرائح المعرض',
    govbh_close_gallery: 'إغلاق المعرض',
    govbh_max_files_allowed: 'الحد الأقصى المسموح به للملفات هو {0}',
    govbh_file_exceeds: 'الملف {0} {1} يتجاوز حجمه {2} ميجابايت',
}